Bug/spring boot pom dependency management error & gitignore
garyorsargos/carver-matrix pull request #10
Opened 2024-11-04 15:59 UTC by Rickory2021

Added to .gitignore for all .env and node_module

To hide errors inside pom.xml
Based on Recommendation of Starter App
- Introduced a `<dependencyManagement>` section in the `pom.xml` to manage versions for `spring-webmvc` and `xmlunit-core`.
- Set the version for `spring-webmvc` to `6.1.13` for consistency across the project.
- Set the version for `xmlunit-core` to `2.10.0` to ensure the latest stable version is used where applicable.
- This change simplifies dependency declarations in the rest of the project by centralizing the versioning of key dependencies.
266e262
backend\pom.xml

2024-11-05 05:14 UTC, tranpham9 requested changes
We may need to update the .gitignore again

2024-11-05 05:14 UTC, tranpham9 commented on dev/tls/rootCA.crt
I believe this information was not supposed to be committed to the repo

2024-11-05 05:33 UTC, Rickory2021 commented on dev/tls/rootCA.crt
Information has now been removed.

2024-11-06 03:39 UTC, tranpham9 approved these changes

2024-11-06 03:40 UTC, merged